### ISSUE TITLE
Graceful handling on network hiccups

### ISSUE THREAD

**Issue by unnawut** [omgnetwork/elixir-omg#1346]
These processes recovered fine on connectivity errors, but it's spamming the logs.

Graceful handling of these connectivity issues should reduce unnecessary logging and so we don't miss important logs.

**EthereumEventListener:**

```elixir
2020-02-25 03:05:03.879 [error] module=gen_server function=error_info/7 trace_id=7827200034090298291 span_id=7506181750154820966 ⋅GenServer :depositor terminating
** (MatchError) no match of right hand side value: {:error, :connect_timeout}
(omg_eth) lib/omg_eth/root_chain/rpc.ex:38: OMG.Eth.RootChain.Rpc.get_ethereum_events/4
(omg_eth) lib/omg_eth/root_chain.ex:139: OMG.Eth.RootChain.get_deposits/3
(omg) lib/omg/ethereum_event_listener.ex:179: OMG.EthereumEventListener.maybe_update_event_cache/2
(omg) lib/omg/ethereum_event_listener.ex:164: OMG.EthereumEventListener.sync_height/3
(omg) lib/omg/ethereum_event_listener.ex:149: OMG.EthereumEventListener.handle_info/2
(stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
(stdlib) gen_server.erl:711: :gen_server.handle_msg/6
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :sync⋅
```

**BlockQueue:**

```elixir
2020-02-25 03:05:03.934 [error] module=gen_server function=error_info/7 ⋅GenServer OMG.ChildChain.BlockQueue.Server terminating
** (MatchError) no match of right hand side value: {:error, :connect_timeout}
(omg_child_chain) lib/omg_child_chain/block_queue.ex:166: OMG.ChildChain.BlockQueue.Server.handle_info/2
(stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
(stdlib) gen_server.erl:711: :gen_server.handle_msg/6
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :check_ethereum_status⋅
```

**BlockGetter:**

```elixir
2020-02-25 03:05:11.940 [error] module=gen_server function=error_info/7 trace_id=3524599526650142990 span_id=877962422177612146 ⋅GenServer OMG.Watcher.BlockGetter terminating
** (MatchError) no match of right hand side value: {:error, :timeout}
(omg_eth) lib/omg_eth/root_chain/rpc.ex:38: OMG.Eth.RootChain.Rpc.get_ethereum_events/4
(omg_eth) lib/omg_eth/root_chain.ex:161: OMG.Eth.RootChain.get_block_submitted_events/2
(omg_watcher) lib/omg_watcher/block_getter.ex:310: OMG.Watcher.BlockGetter.get_block_submitted_events/1
(omg_watcher) lib/omg_watcher/block_getter.ex:280: OMG.Watcher.BlockGetter.do_sync/1
(stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
(stdlib) gen_server.erl:711: :gen_server.handle_msg/6
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :sync⋅
```

```elixir
FunctionClauseError: no function clause matching in OMG.Watcher.BlockGetter.handle_info/2
  File "lib/omg_watcher/block_getter.ex", line 232, in OMG.Watcher.BlockGetter.handle_info/2
  File "gen_server.erl", line 637, in :gen_server.try_dispatch/4
  File "gen_server.erl", line 711, in :gen_server.handle_msg/6
  File "proc_lib.erl", line 249, in :proc_lib.init_p_do_apply/3
```

**Comment by anarmanafov1** [comment]
I would like to take this on. 

When you handling these gracefully, do you mean mute/change the log message?

**Comment by anarmanafov1** [comment]
@unnawut I am also unsure how a process can recover from a time out. Could you explain? Thanks.

**Comment by unnawut** [comment]
Thanks @anarmanafov1 for your interest! Please note that with this recent PR https://github.com/omisego/elixir-omg/pull/1376 we'll be consolidating these separate calls and so the mechanism here would have changed.

Our recommendation would be to follow that PR and start looking into this issue again once that PR has landed. Thanks again!

**Comment by anarmanafov1** [comment]
Ok thanks, will do.

**Comment by unnawut** [comment]
Calls consolidated in #1376. Hasn't seen this issue resurfaced in a while. Thank you!

**Comment by pgebal** [comment]
It's back: https://sentry.io/organizations/omisego/issues/1540269873/?project=1477673

**Comment by InoMurko** [comment]
this isn't back, it's just solved in the next release. 
![Uploading Screen Shot 2020-06-09 at 19.35.32.png…]()
