### ISSUE TITLE
StatusCache race condition on startup

### ISSUE THREAD

**Issue by InoMurko** [omgnetwork/elixir-omg#1557]
StatusCache immediately asks for status of the underlying services. Even though these services start the bootup before StatusCache, their startup is async.
Look at BlockGetter `handle_continue(:setup, args)`.

```
2020-06-01 10:55:02.172 [info] module=OMG.EthereumEventListener function=handle_continue/2 ⋅Started OMG.EthereumEventListener for piggyback_processor, synced_height: 22⋅
 
 2020-06-01 10:55:02.175 [info] module=OMG.Watcher.BlockGetter function=handle_continue/2 ⋅Started OMG.Watcher.BlockGetter, synced_height: 22 maximum_block_withholding_time_ms: 54000000⋅
 
 2020-06-01 10:55:02.177 [info] module=application_controller function=info_exited/3 ⋅Application omg_watcher exited: OMG.Watcher.Application.start(:normal, []) returned an error: shutdown: failed to start child: OMG.Watcher.Supervisor
 
    ** (EXIT) shutdown: failed to start child: OMG.Watcher.Monitor
 
        ** (EXIT) an exception was raised:
 
            ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, OMG.Watcher.API.StatusCache, {:noproc, {GenServer, :call, [OMG.Watcher.BlockGetter.Status, {:get, #Function<0.22313787/1 in OMG.Watcher.BlockGetter.Status.get_events/0>}, 5000]}}}}}
 
                (omg_watcher 0.4.8) lib/omg_watcher/monitor.ex:106: OMG.Watcher.Monitor.start_child/1
 
                (omg_watcher 0.4.8) lib/omg_watcher/monitor.ex:55: OMG.Watcher.Monitor.init/1
 
                (stdlib 3.12) gen_server.erl:374: :gen_server.init_it/2
 
                (stdlib 3.12) gen_server.erl:342: :gen_server.init_it/6
 
                (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3⋅
 
 [os_mon] memory supervisor port (memsup): Erlang has closed
 
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
 
{"Kernel pid terminated",application_controller,"{application_start_failure,omg_watcher,{{shutdown,{failed_to_start_child,'Elixir.OMG.Watcher.Supervisor',{shutdown,{failed_to_start_child,'Elixir.OMG.Watcher.Monitor',{{badmatch,{error,{shutdown,{failed_to_start_child,'Elixir.OMG.Watcher.API.StatusCache',{noproc,{'Elixir.GenServer',call,['Elixir.OMG.Watcher.BlockGetter.Status',{get,#Fun<Elixir.OMG.Watcher.BlockGetter.Status.0.22313787>},5000]}}}}}},[{'Elixir.OMG.Watcher.Monitor',start_child,1,[{file,\"lib/omg_watcher/monitor.ex\"},{line,106}]},{'Elixir.OMG.Watcher.Monitor',init,1,[{file,\"lib/omg_watcher/monitor.ex\"},{line,55}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}}}},{'Elixir.OMG.Watcher.Application',start,[normal,[]]}}}"} 
Kernel pid terminated (application_controller) ({application_start_failure,omg_watcher,{{shutdown,{failed_to_start_child,'Elixir.OMG.Watcher.Supervisor',{shutdown,{failed_to_start_child,'Elixir.OMG.Wa 
 
Crash dump is being written to: erl_crash.dump...done 
Makefile:406: recipe for target 'start-watcher_info' failed
 
make: *** [start-watcher_info] Error 1
 
```

**Comment by unnawut** [comment]
Closed by #1558
